#include "db_sqlite.h"
#include <stdio.h>
#include <sqlite3.h>

static sqlite3 *db;

int db_init(const char *db_path) {
    int rc = sqlite3_open(db_path, &db);
    if (rc) {
        fprintf(stderr, "Can't open database: %s\n", sqlite3_errmsg(db));
        return 0;
    }

    // Create the attacks table
    const char *sql = "CREATE TABLE IF NOT EXISTS attacks ("
                      "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                      "timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,"
                      "ip TEXT,"
                      "scan_type TEXT,"
                      "risk_level TEXT,"
                      "action TEXT);";

    char *err_msg = NULL;
    rc = sqlite3_exec(db, sql, 0, 0, &err_msg);
    
    if (rc != SQLITE_OK) {
        fprintf(stderr, "SQL error: %s\n", err_msg);
        sqlite3_free(err_msg);
        return 0;
    }
    
    return 1;
}

int db_insert_event(const char *ip_str, const char *scan_type, const char *risk_level, const char *action) {
    if (!db) return 0;

    char sql[512];
    // We use snprintf since all inputs are strictly generated by our program (no user input = no SQL injection risk)
    snprintf(sql, sizeof(sql), 
             "INSERT INTO attacks (ip, scan_type, risk_level, action) VALUES ('%s', '%s', '%s', '%s');", 
             ip_str, scan_type, risk_level, action);

    char *err_msg = NULL;
    int rc = sqlite3_exec(db, sql, 0, 0, &err_msg);
    
    if (rc != SQLITE_OK) {
        fprintf(stderr, "Failed to insert into DB: %s\n", err_msg);
        sqlite3_free(err_msg);
        return 0;
    }
    
    return 1;
}