#!/bin/bash

# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Error: Please run this script as root (sudo)."
  exit 1
fi

echo "[*] Cleaning up IPTables rules generated by the Defense Engine..."

# 1. Flush the default filter table (Removes LOG and DROP rules)
iptables -t filter -F INPUT

# 2. Flush the NAT table (Removes REDIRECT to honeypot rules)
iptables -t nat -F PREROUTING

# 3. Optional: List the current rules to verify they are gone
echo "[*] Current INPUT rules:"
iptables -L INPUT -n

echo "[*] Current NAT PREROUTING rules:"
iptables -t nat -L PREROUTING -n

echo "[+] Cleanup complete!"